### ISSUE TITLE
macos10.15.4无法打开

### ISSUE THREAD

**Issue by hackenfu** [zekunyan/TTGBingWallPaper#10]
老的macos系统我没有试过，今天是第一次看到您的作品

**Comment by jirrick** [comment]
Run this in terminal
`chmod +x /Applications/BingWallPaper.app/Contents/MacOS/BingWallPaper`

**Comment by hackenfu** [comment]
> Run this in terminal
> `chmod +x /Applications/BingWallPaper.app/Contents/MacOS/BingWallPaper`

after running this, it shows "the app is broken, please move it to the trash"

**Comment by jirrick** [comment]
Full steps what I did, based on multiple threads & forums, not sure everything is actually needed:
* Run this in terminal before unzipping: `xattr -d com.apple.quarantine /Users/jirrick/Downloads/BingWallPaper.app.zip`
* Unzip using 7zip (installer via homebrew) `7za x BingWallPaper.app.zip`
* Move to Applications
* Run `chmod +x /Applications/BingWallPaper.app/Contents/MacOS/BingWallPaper`

![Screenshot 2020-03-28 at 16 50 43](https://user-images.githubusercontent.com/1150547/77827178-72f27b80-7114-11ea-9836-3984c98be917.png)

**Comment by hackenfu** [comment]
> Full steps what I did, based on multiple threads & forums, not sure everything is actually needed:
> 
> * Run this in terminal before unzipping: `xattr -d com.apple.quarantine /Users/jirrick/Downloads/BingWallPaper.app.zip`
> * Unzip using 7zip (installer via homebrew) `7za x BingWallPaper.app.zip`
> * Move to Applications
> * Run `chmod +x /Applications/BingWallPaper.app/Contents/MacOS/BingWallPaper`
> 
> ![Screenshot 2020-03-28 at 16 50 43](https://user-images.githubusercontent.com/1150547/77827178-72f27b80-7114-11ea-9836-3984c98be917.png)

works. many thanks.

**Comment by zekunyan** [comment]
@hackenfu 下最新版的0.5.1，然后执行`codesign --force --deep --sign - /Applications/BingWallPaper.app`试试

**Comment by hackenfu** [comment]
> @hackenfu 下最新版的0.5.1，然后执行`codesign --force --deep --sign - /Applications/BingWallPaper.app`试试

无法打开xxx，因为apple无法检查其是否包含恶意软件
不过我去安全设置里强制打开，还是可以用了的。多谢作者！

**Comment by zekunyan** [comment]
@hackenfu 嗯嗯，签名问题管得越来越严格了
