### ISSUE TITLE
如何让他每天自动获取新的壁纸

### ISSUE THREAD

**Issue by zhang2853** [zekunyan/TTGBingWallPaper#11]
首先感谢大佬的贡献， 我找这个APP真的 找了很久了。 哈哈。 

现在使用起来都很方便， 想请教一下 如何能让他每天自动获取 壁纸呢？ 或者自动获取的时间是什么时候。 我现在只能每天手动获取。

**Comment by zekunyan** [comment]
默认有自动更新的逻辑的

**Comment by call-me-nobody** [comment]
我大概看了一眼代码 每12个小时更新一次， 请我一下  折合成北京时间  是每天几点和几点更新呢？

**Comment by zhang2853** [comment]
我大概看了一眼代码 每12个小时更新一次， 请问一下 折合成北京时间 是每天几点和几点更新呢？

**Comment by zekunyan** [comment]
@zhang2853 没有准确时间，就是打开的时候往后12小时，没有做这么精确=。=，欢迎PR

**Comment by zhang2853** [comment]
PR 就算了 不会写代码。 哈哈  谢谢大佬
